# dotfilesã§ç®¡ç†ã™ã‚‹~/.config/starship.toml

# Don't print a new line at the start of the prompt
add_newline = false

command_timeout = 1500

[aws]
format = "on [$symbol$profile]($style) "
symbol = "â˜ï¸ "
disabled = true

[gcloud]
format = "on [$symbol$project]($style) "
symbol = "â˜ï¸ "

[kubernetes]
symbol = "â›µ "
style = "dim green"
disabled = false

[terraform]
symbol = "ğŸŒ "

[nodejs]
symbol = "ğŸ§µ "
disabled = true

[git_branch]
symbol = "ğŸŒ± "

[ruby]
disabled = true
