# ~/.config/starship.toml
# Don't print a new line at the start of the prompt
add_newline = false

command_timeout=1500

[kubernetes]
symbol = "â›µ"
style = "dim green"
disabled = false

[terraform]
symbol = "ğŸŒ"

[nodejs]
symbol = "ğŸ§µ"

[git_branch]
symbol = "ğŸŒ±"
